version: "3"

services:
  queue:
    user: $UID:$GID
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE=3WzUFfk71jdJxjMjhNsT
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=j8XfG9ZDT5ZZrWTzw62q
    ports:
      - 15672:15672

  services:
    user: $UID:$GID
    build:
      context: ..
      dockerfile: wheat_rust_bot/Dockerfile
    command: python services.py
    depends_on:
      - queue

  web:
    user: $UID:$GID
    build:
      context: ..
      dockerfile: wheat_rust_bot/Dockerfile
    command: uvicorn web:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - services

  tgbot:
    user: $UID:$GID
    build:
      context: ..
      dockerfile: wheat_rust_bot/Dockerfile
    environment:
      TG_TOKEN: ${TG_TOKEN}
    command: python tgbot.py
    depends_on:
      - services
    volumes:
      - ../imgs:/imgs

volumes:
  imgs:
